# Generated by Django 4.0.4 on 2022-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_rename_post_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='texts',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
